// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileoverview A Genkit Next.js API route handler.
 */

import {genkit} from '@/ai/genkit';
import {nextJSHandler} from '@genkit-ai/next';

export const {GET, POST} = nextJSHandler({genkit});
