// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to initiate a background check for a user.
 *
 * - initiateBackgroundCheck - A function that handles the background check process.
 * - BackgroundCheckInput - The input type for the initiateBackgroundCheck function.
 * - BackgroundCheckOutput - The return type for the initiateBackgroundCheck function.
 */

import {ai} from '@/ai/genkit';
import { BackgroundCheckInputSchema, BackgroundCheckOutputSchema, type BackgroundCheckInput, type BackgroundCheckOutput } from '@/lib/types';


export async function initiateBackgroundCheck(input: BackgroundCheckInput): Promise<BackgroundCheckOutput> {
  return initiateBackgroundCheckFlow(input);
}

const initiateBackgroundCheckFlow = ai.defineFlow(
  {
    name: 'initiateBackgroundCheckFlow',
    inputSchema: BackgroundCheckInputSchema,
    outputSchema: BackgroundCheckOutputSchema,
  },
  async (input) => {
    // IMPORTANT: In a real application, get the API key from a secure location like environment variables.
    const apiKey = process.env.BACKGROUND_CHECKS_API_KEY;

    if (!apiKey) {
      console.error("Background Checks API key is missing.");
      return {
        success: false,
        message: "Server configuration error: API key is missing.",
      };
    }
    
    const apiUrl = 'https://api.backgroundchecks.com/v2/orders';

    const requestBody = {
        "candidate": {
            "first_name": input.firstName,
            "middle_name": input.middleName,
            "last_name": input.lastName,
            "ssn": input.ssn,
            "dob": input.dob,
            "address": input.address,
            "city": input.city,
            "state": input.state,
            "zip": input.zip
        },
        "order_detail": {
            "reference_code": `mymasjid-user-${Date.now()}`
        },
        "searches": [
            { "search_type": "criminal_database", "search_qualifier": "natl" },
            { "search_type": "sex_offender_database", "search_qualifier": "natl" }
        ]
    };

    try {
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
        },
        body: JSON.stringify(requestBody),
      });

      const responseData = await response.json();

      if (!response.ok) {
        console.error("Background check API error:", responseData);
        return {
          success: false,
          message: responseData.message || 'Failed to initiate background check.',
        };
      }
      
      return {
        success: true,
        reportId: responseData.order_id,
        message: 'Background check initiated successfully!',
      };

    } catch (error) {
      console.error("Error calling background check API:", error);
      return {
        success: false,
        message: 'An unexpected error occurred.',
      };
    }
  }
);
